version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"] 
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432"]

volumes:
  postgresdata:
